### ISSUE TITLE
add Travis build status badge to README

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#37]
Once we start testing the commands (#22, #34, #35, #36), we should add a [Travis build status badge](http://docs.travis-ci.com/user/status-images/) to the README.

**Comment by mykmelez** [comment]
There are a ton of other badges we might add, such as those implemented by the [badges module](https://www.npmjs.com/package/badges) and those supported by http://shields.io/. But the Travis one is the only one that I know would be useful to advertise.

**Comment by marco-c** [comment]
I've found the _dependencies_ and _devDependencies_ badges to be useful too (for example I once chose a library over another because the green badges meant the library was actively developed).

A code coverage badge would be useful too to advertise the level of quality of the library, but we currently have 0% coverage :smile:
